#!/usr/bin/env bash
# Submit every job.slurm generated by ./generate_jobs.sh to Slurm.
#
# Usage:
#   ./generate_jobs.sh   # first, to create runs/n<N>_shots<S>/job.slurm
#   ./submit_all.sh
set -euo pipefail

CLUSTER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNS_DIR="$CLUSTER_DIR/runs"

if ! command -v sbatch >/dev/null 2>&1; then
  echo "sbatch not found. Run this on a login node of your Slurm cluster." >&2
  exit 1
fi

shopt -s nullglob
jobs=("$RUNS_DIR"/*/job.slurm)
shopt -u nullglob

if [ ${#jobs[@]} -eq 0 ]; then
  echo "No job.slurm files found under $RUNS_DIR." >&2
  echo "Run ./generate_jobs.sh first." >&2
  exit 1
fi

log_file="$RUNS_DIR/submitted_jobs.tsv"
printf 'job_id\tfolder\n' > "$log_file"

submitted=0
for job in "${jobs[@]}"; do
  dir="$(dirname "$job")"
  job_id="$(sbatch --parsable "$job")"
  printf '%s -> %s\n' "$job_id" "$dir"
  printf '%s\t%s\n' "$job_id" "$dir" >> "$log_file"
  submitted=$((submitted + 1))
done

echo
echo "Submitted $submitted job(s). IDs and folders saved to $log_file"
echo 'Track them with: squeue -u $USER'
